In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot
import seaborn as sns

In [3]:
df=pd.read_csv("customer_churn_.csv")
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [4]:
# customerID: A unique identifier for each customer.
# gender: The gender of the customer (Male/Female).
# SeniorCitizen: Indicates if the customer is a senior citizen (1 = Yes, 0 = No).
# Partner: Indicates if the customer has a partner (Yes/No).
# Dependents: Indicates if the customer has dependents (Yes/No).
# tenure: Number of months the customer has stayed with the company.
# PhoneService: Indicates if the customer has a phone service (Yes/No).
# MultipleLines: Indicates if the customer has multiple lines (Yes/No/No phone service).
# InternetService: Type of internet service (DSL, Fiber optic, None).
# OnlineSecurity: Indicates if the customer has online security add-ons (Yes/No/No internet service).
# DeviceProtection: Indicates if the customer has device protection add-ons (Yes/No/No internet service).
# TechSupport: Indicates if the customer has tech support add-ons (Yes/No/No internet service).
# StreamingTV: Indicates if the customer streams TV services (Yes/No/No internet service).
# StreamingMovies: Indicates if the customer streams movies (Yes/No/No internet service).
# Contract: Type of contract (Month-to-month, One year, Two year).
# PaperlessBilling: Indicates if the customer uses paperless billing (Yes/No).
# PaymentMethod: The payment method used (e.g., Electronic check, Mailed check, Bank transfer, Credit card).
# MonthlyCharges: Monthly charges for the customer.
# TotalCharges: Total charges billed to the customer.
# Churn: Indicates if the customer has churned (Yes/No).

In [5]:
# STEP : 3 EDA(EXPLORATORY DATA ANALYSIS)
# 1.null
# 2.duplicates
# 3.outliers
# 4.encoding

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [7]:
df.isnull().sum().sum()

np.int64(0)

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
#STEP:4 DATA PREPROCESSING

# REMOVE THE EXTRA COLUMN
df.drop(columns=['customerID'],inplace=True)

In [10]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [15]:
# ENCODING - it is of three types
# 1. label encoding = will use alphabetical order
#     apple=0
#     cherry=3
#     banana=2
# 2. ordinal encoding = will use order provided by user 
#     low=0
#     high=2
#     med=1
# 3. one hot encoding = it will create extra columns and then it will encode it 
#     status           single    married   relationship
#     single              1        0           0
#     married             0        1           0
#     relationship        0        0           1

In [16]:
# ENCODING - CONVERTING CATEGORICAL DATA TO NUMERICAL DATA 
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in df.columns:
    if df[i].dtype=='object':
        df[i]=le.fit_transform(df[i])

In [12]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,2505,0
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1466,0
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,157,1
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1400,0
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,925,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,2,0,2,0,2,2,2,2,1,1,3,84.80,1597,0
7039,0,0,1,1,72,1,2,1,0,2,2,0,2,2,1,1,1,103.20,5698,0
7040,0,0,1,1,11,0,1,0,2,0,0,0,0,0,0,1,2,29.60,2994,0
7041,1,1,1,0,4,1,2,1,0,0,0,0,0,0,0,1,3,74.40,2660,1
7042,1,0,0,0,66,1,0,1,2,0,2,2,2,2,2,1,0,105.65,5407,0

In [20]:
# STEP:5 (DATA SPLITTING FOR MODEL BUILDING)
x=df.drop("Churn",axis=1) # independent variable
y=df['Churn'] # dependent variable

In [21]:
x

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,2505
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1466
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,157
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1400
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,925
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,2,0,2,0,2,2,2,2,1,1,3,84.80,1597
7039,0,0,1,1,72,1,2,1,0,2,2,0,2,2,1,1,1,103.20,5698
7040,0,0,1,1,11,0,1,0,2,0,0,0,0,0,0,1,2,29.60,2994
7041,1,1,1,0,4,1,2,1,0,0,0,0,0,0,0,1,3,74.40,2660
7042,1,0,0,0,66,1,0,1,2,0,2,2,2,2,2,1,0,105.65,5407

In [22]:
y

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

In [24]:
# divide my data into training and testing data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0) # random state = to shuffle the data , test size= 0.2 mean 20% data goes for testing

In [28]:
# STEP:6 MODEL TRAINING AND TESTING
from sklearn.ensemble import RandomForestClassifier
model_1=RandomForestClassifier()

# TRAIN THE MODEL 
model_1.fit(x_train,y_train)

# ASK THE MODEL TO PREDICT 
y_pred= model_1.predict(x_test)

# EVALUATING THE PERFORMANCE BY COMPARING THE PREDICTED VALUE WITH THE ACTUAL VALUE
from sklearn.metrics import *
print("Accuracy Score of the model is :", accuracy_score(y_pred , y_test)*100)

Accuracy Score of the model is : 78.35344215755855

In [29]:
df1=pd.DataFrame()
df1['ACTUAL Value']=y_test
df1['Predicted Value']=y_pred
df1

      ACTUAL Value  Predicted Value
2200             0                0
4627             0                0
3225             0                0
2828             0                0
3768             0                0
...            ...              ...
2631             1                1
5333             1                1
6972             1                0
4598             0                0
3065             0                1

[1409 rows x 2 columns]

In [31]:
from sklearn.linear_model import LogisticRegression
df2=LogisticRegression()
df2.fit(x_train,y_train)

C:\Users\ARYAN SHARMA\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [34]:
y_predi=df2.predict(x_test)
from sklearn.metrics import *
print("Accuracy Score is :", accuracy_score(y_test , y_predi)*100)

Accuracy Score is : 78.49538679914833

In [35]:
m=pd.DataFrame()
m['Actual Values']=y_test
m['Predicted Values']=y_predi
m

      Actual Values  Predicted Values
2200              0                 0
4627              0                 0
3225              0                 1
2828              0                 0
3768              0                 0
...             ...               ...
2631              1                 1
5333              1                 1
6972              1                 0
4598              0                 0
3065              0                 1

[1409 rows x 2 columns]

In [36]:
from sklearn.tree import DecisionTreeClassifier
df3=DecisionTreeClassifier()
df3.fit(x_train,y_train)

DecisionTreeClassifier()

In [38]:
y_predic=df3.predict(x_test)
from sklearn.metrics import *
print(" Accuracy score is ", accuracy_score(y_test,y_predic))

 Accuracy score is  0.7182398864442867

In [39]:
mo=pd.DataFrame()
mo['Actual Value']=y_test
mo['Predicted Value']=y_predic
mo

      Actual Value  Predicted Value
2200             0                0
4627             0                0
3225             0                0
2828             0                0
3768             0                1
...            ...              ...
2631             1                1
5333             1                0
6972             1                1
4598             0                0
3065             0                1

[1409 rows x 2 columns]

***accuracy score of random forest is best***

***now i will explore some hyperparameter which help my accuracy score become optimul***

***hyperparameter of sklearn for RandomForest includes :***

***n_estimators : The n_estimators hyperparameter in a random forest model defines the number of decision trees to build before combining their predictions , by default n_estimators sets on 100***

In [49]:
# let see how n_estimator  our accuracy score of random forest
# STEP:6 MODEL TRAINING AND TESTING
from sklearn.ensemble import RandomForestClassifier
model_1=RandomForestClassifier(n_estimators=200, criterion='entropy',max_depth=10,min_samples_leaf=5,min_samples_split=5)

# TRAIN THE MODEL 
model_1.fit(x_train,y_train)

# ASK THE MODEL TO PREDICT 
y_pred= model_1.predict(x_test)

# EVALUATING THE PERFORMANCE BY COMPARING THE PREDICTED VALUE WITH THE ACTUAL VALUE
from sklearn.metrics import *
print("Accuracy Score of the model is :", accuracy_score(y_pred , y_test)*100)

Accuracy Score of the model is : 79.55997161107167

***The "criterion" in a random forest is the function used to measure the quality of a split at each node of the decision trees within the forest. The algorithm aims to maximize information gain or minimize impurity with each split.***
***it includes Gini Impurity (the default) and Entropy (or Information Gain)***

***max_depth: This parameter sets the maximum number of levels in each decision tree.***

***A shallow tree (low max_depth) may underfit the data, failing to capture complex patterns.***

***A deep tree (high max_depth or default None in scikit-learn, which means unlimited depth until leaves are pure) is more complex and likely to overfit the training data by capturing noise.***

***tuning this helps find the optimal balance between underfitting and overfitting.***

***min_samples_split: This defines the minimum number of samples an internal node must contain before it can be split into a left and right branch.***

**If a node has fewer samples than the specified minimum, the split is not allowed, and the node becomes a leaf node.***

***Increasing this value makes the tree less prone to capturing fine-grained details in the training data, acting as a form of regularization to prevent overfitting. The default value in scikit-learn is 2.***

***min_samples_leaf: This specifies the minimum number of samples that must be present in each resulting leaf node after a split.***

***Even if a potential split satisfies the min_samples_split condition, it will be rejected if it results in any leaf node having fewer samples than min_samples_leaf.***

***This ensures that the final leaf nodes are not based on an arbitrarily small number of samples, providing a stronger guarantee of a minimum number of samples in every leaf than min_samples_split alone. The default value in scikit-learn is 1.***

In [52]:
paramaters_grid = {
    'n_estimators': [100, 200, 500, 1000],
    'max_depth': [10, 20, 30],  # None means trees are grown to full depth
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'criterion': ['gini', 'entropy']
}

In [ ]:
from sklearn.model_selection import GridSearchCV
model=RandomForestClassifier()
gridsearch=GridSearchCV(estimator=model , param_grid=paramaters_grid)
gridsearch.fit(x_train,y_train)
print(" best parameter values are :", grid_search.best_params_)

***GridSearchCV provides the best hyper paramaters***